import type { PilotProfile, SortieRecord, PilotSnapshot } from "./types";

function daysFromNow(d: number): string {
  const t = new Date();
  t.setDate(t.getDate() + d);
  return t.toISOString().slice(0, 10);
}

export const DEMO_MILITARY_NUMBER = "P001";
export const DEMO_LINK_CODE = "123456";

const demoProfile: PilotProfile = {
  id: "P001",
  militaryNumber: "P001",
  name: "Tariq Al-Masri",
  arabicName: "طارق المصري",
  rank: "Capt",
  unit: "SQDN",
  squadron: "8th Sqn",
  phone: "0791234567",
  openingDay: 1240.4,
  openingNight: 312.1,
  openingNvg: 198.6,
  openingCaptain: 740.0,
  openingSim: 84.3,
  expiry: {
    day: daysFromNow(45),
    night: daysFromNow(12),
    nvg: daysFromNow(7),
    irt: daysFromNow(-3),
    medical: daysFromNow(120),
    sim: daysFromNow(28),
  },
};

const demoSorties: SortieRecord[] = [
  {
    id: "S10001",
    date: daysFromNow(-2),
    acType: "UH-60M",
    acNumber: "832",
    sortieType: "Training",
    name: "NVG",
    pilotIsCaptain: true,
    day: 0,
    night: 0,
    nvg: 1.6,
    sim: 0,
    total: 1.6,
  },
  {
    id: "S10002",
    date: daysFromNow(-5),
    acType: "UH-60M",
    acNumber: "812",
    sortieType: "Mission",
    name: "MSN DAY",
    pilotIsCaptain: true,
    day: 2.4,
    night: 0,
    nvg: 0,
    sim: 0,
    total: 2.4,
  },
  {
    id: "S10003",
    date: daysFromNow(-9),
    acType: "UH-60AIL",
    acNumber: "841",
    sortieType: "Check Ride",
    name: "EVAL",
    pilotIsCaptain: false,
    day: 1.8,
    night: 0,
    nvg: 0,
    sim: 0,
    total: 1.8,
  },
  {
    id: "S10004",
    date: daysFromNow(-14),
    acType: "UH-60M",
    acNumber: "807",
    sortieType: "Training",
    name: "IF",
    pilotIsCaptain: true,
    day: 0,
    night: 1.5,
    nvg: 0,
    sim: 0,
    total: 1.5,
  },
  {
    id: "S10005",
    date: daysFromNow(-21),
    acType: "UH-60M",
    acNumber: "832",
    sortieType: "Training",
    name: "NAV",
    pilotIsCaptain: true,
    day: 2.0,
    night: 0,
    nvg: 0,
    sim: 0,
    total: 2.0,
  },
  {
    id: "S10006",
    date: daysFromNow(-28),
    acType: "UH-60M",
    acNumber: "832",
    sortieType: "Training",
    name: "NVG",
    pilotIsCaptain: false,
    day: 0,
    night: 0,
    nvg: 1.4,
    sim: 0,
    total: 1.4,
  },
  {
    id: "S10007",
    date: daysFromNow(-40),
    acType: "AS332",
    acNumber: "806",
    sortieType: "Mission",
    name: "MSN DAY",
    pilotIsCaptain: true,
    day: 2.7,
    night: 0,
    nvg: 0,
    sim: 0,
    total: 2.7,
  },
  {
    id: "S10008",
    date: daysFromNow(-50),
    acType: "UH-60M",
    acNumber: "812",
    sortieType: "Training",
    name: "SIM",
    pilotIsCaptain: false,
    day: 0,
    night: 0,
    nvg: 0,
    sim: 2.0,
    total: 2.0,
  },
];

export const demoSnapshot: PilotSnapshot = {
  profile: demoProfile,
  sorties: demoSorties,
  notams: [
    {
      id: "N-2026-014",
      date: new Date().toISOString().slice(0, 10),
      text: "Runway 26L closed for maintenance from 0600–1000Z. Use 26R for all departures and arrivals.",
    },
    {
      id: "N-2026-013",
      date: new Date(Date.now() - 86400000).toISOString().slice(0, 10),
      text: "تنبيه: تدريبات إطلاق ليلية في منطقة التدريب (شرق) من الساعة 20:00 حتى 23:00. يُمنع الطيران تحت ارتفاع 3000 قدم.",
    },
  ],
  alerts: [
    {
      id: "A-2026-009",
      postedAt: new Date().toISOString(),
      text: "Weather brief moved to 0530Z. All crews report to ops 30 minutes earlier.",
      author: "Squadron Cmdr",
    },
    {
      id: "A-2026-008",
      postedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
      text: "تنبيه: اجتماع طارئ لجميع طياري السرب الساعة الثانية بعد الظهر. الحضور إلزامي.",
      author: "Flight Cmdr",
    },
  ],
  fetchedAt: new Date().toISOString(),
};
